### ISSUE TITLE
RE can't add missions why not

### ISSUE THREAD

**Issue by aaronliunumber2** [aaronliunumber2/foundrymissions#10]
Something is wrong he can'ta dd missions

**Comment by aaronliunumber2** [comment]
Cryptic ID validation, investigate this

**Comment by aaronliunumber2** [comment]
RogueEnterprise - Today at 2:50 PM
no
i think it was giving me the wrong validation message
cuz it says only letters andn umbers or whatever
but the problem was that it has to be 9 charas

**Comment by RogueEnterprise** [comment]
This is happening because the validation messaging was incorrect. I will submit a separate issue for this.
