### ISSUE TITLE
Need new icons!

### ISSUE THREAD

**Issue by aaronliunumber2** [aaronliunumber2/foundrymissions#14]

**Comment by RogueEnterprise** [comment]
Icons were provided. Requesting revisions for Combat, Ground, No Combat and Story.

**Comment by aaronliunumber2** [comment]
Added them tag logos
Romulan and Reman logos are missing

**Comment by aaronliunumber2** [comment]
Remaining Icons.
Rank Logos - Rank logo should depend on level and faction
Faction Logos
Site Logo
Twitter/Avatar Logo
Favicon

**Comment by RogueEnterprise** [comment]
All tag icons have been provided. I suggest we close this and tackle each new request as it comes in from to do, as they are all listed in the backlog. Closing
