### ISSUE TITLE
Some icons on mission view page do not update correctly

### ISSUE THREAD

**Issue by RogueEnterprise** [aaronliunumber2/foundrymissions#26]
When viewing any mission, the image shows captain rank no matter how the level requirement is configured.

Example: http://www.foundrymissions.com/missions/orders--part-i

**Comment by aaronliunumber2** [comment]
Same with the faction logo

**Comment by RogueEnterprise** [comment]
Can we fix this by using the low res rank images for now? We will need a new KDF faction graphic though.

**Comment by aaronliunumber2** [comment]
done
