### ISSUE TITLE
Mission duration not displayed on mission detail view page

### ISSUE THREAD

**Issue by RogueEnterprise** [aaronliunumber2/foundrymissions#3]
The user is able to configure a mission duration on the submission/edit view but that information does not display on the mission detail view page.

Note: This wasn't in my mockup. Maybe we can set this up with an icon that shows up just below the tags box on the right side?

**Comment by aaronliunumber2** [comment]
Damn this was reported 24 days ago.

I wanna leave this to the next version so I can focus on bugs

**Comment by RogueEnterprise** [comment]
I think we should probably still address it before the first release. Can we hide from the edit page until it's enabled in the view screen?

**Comment by RogueEnterprise** [comment]
This also applies to Published status, Spotlit status,

**Comment by aaronliunumber2** [comment]
Mission length now listed in the mission view page as text under the title
