### ISSUE TITLE
Replace site logo

### ISSUE THREAD

**Issue by RogueEnterprise** [aaronliunumber2/foundrymissions#39]
Waiting on me to get the logo delivered.

**Comment by RogueEnterprise** [comment]
![banner](https://cloud.githubusercontent.com/assets/19982318/17012687/3ebfaa66-4ece-11e6-8029-91724e3a155b.png)
Banner ready.

**Comment by aaronliunumber2** [comment]
change the favicon while i'm at it

**Comment by aaronliunumber2** [comment]
Updated logos
