### ISSUE TITLE
"Contact Us" on the main page results in an error

### ISSUE THREAD

**Issue by RogueEnterprise** [aaronliunumber2/foundrymissions#5]
Clicking "Contact Us" on the main page results in an error page.

Steps to reproduce:
1. Go to the main page (currently http://fmv001.azurewebsites.net/)
2. Select "Contact Us" in the header

Result: Error page starting with "Server Error in '/' Application."
Expected: User either sees a form that they can use to email us, or experience a mailto: link

**Comment by aaronliunumber2** [comment]
Made a temporary page for contact us
