### ISSUE TITLE
Redesign main page to include blurb and latest updates

### ISSUE THREAD

**Issue by RogueEnterprise** [aaronliunumber2/foundrymissions#53]
This task is to do a minor restyling of the main page to include two new sections:
1. Latest updates (patch notes-ish)
2. About-the-site text blurb

I'll come up with a few mockups and we can take a look before deciding how we should proceed.

**Comment by RogueEnterprise** [comment]
![newhomepage1](https://cloud.githubusercontent.com/assets/19982318/18337362/b1d7cf82-7544-11e6-8e98-951d0359a1d1.png)

Here's the new layout we agreed on. Make it so!

**Comment by RogueEnterprise** [comment]
This is on prod, but I'd like the ability for each date entry to have several "bullets" like on the mockup I sent.

**Comment by RogueEnterprise** [comment]
Also waiting for new shorter main logo...

**Comment by RogueEnterprise** [comment]
New banner is provided, please update!

**Comment by aaronliunumber2** [comment]
I DID IT

**Comment by RogueEnterprise** [comment]
Reopening, need to fix the updates section still

**Comment by aaronliunumber2** [comment]
I don't remember what's wrong

**Comment by RogueEnterprise** [comment]
Updates section seems fine, I blame the developer for not posting when they fixed it.
