### ISSUE TITLE
Cryptic Mission ID validation not working as expected

### ISSUE THREAD

**Issue by aaronliunumber2** [aaronliunumber2/foundrymissions#9]
(major editing by RE)
The Cryptic mission ID field is not validating correctly.

Test case 1: Input the following text string: 12312AAB2ASDFASD#@ or ASDF$#
Result: Validation fails. Error message displays: Cryptic Id must only contain uppercase alphanumeric characters.
Expected: Validation fails. Error message displays: Cryptic ID must only contain uppercase alphanumeric characters. Additional error message displays: Cryptic ID must be 9 characters long.

**Comment by RogueEnterprise** [comment]
There's more here, I'll test more later.

**Comment by aaronliunumber2** [comment]
Dear lord I figured it out.  the regex was looking for numbers or capital letters, but not lower case letters.  So even though the textbox was "ToUpper-ing" the text value in the textbox the value being validated could include lower case.  I just set the regex to allow lower case as well and the controller will make sure to change it to upper case.

Did the same for edit
